# Generated by Django 5.2 on 2025-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_game_image_url_alter_game_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allgamespage', models.TextField(blank=True, null=True)),
                ('detailpage1', models.TextField(blank=True, null=True)),
                ('detailpage2', models.TextField(blank=True, null=True)),
                ('blogads1', models.TextField(blank=True, null=True)),
                ('blogads2', models.TextField(blank=True, null=True)),
                ('gamerivew', models.TextField(blank=True, null=True)),
                ('blogdetailad1', models.TextField(blank=True, null=True)),
                ('blogdetailad2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
